main/app/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.index),
    path('about', views.about)
]

main/main/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('myfile.urls', namespace="fileapp"))
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/myfile/urls.py
from django.urls import path
from . import views
app_name = "fileapp"
urlpatterns = [

    path("", views.index),
    path("upload", views.send_files, name="uploads"),
]

main/app/models.py
from django.db import models

# Create your models here.

main/myfile/models.py
from django.db import models

# Create your models here.

class myuploadfile(models.Model):
    f_name = models.CharField(max_length=255)
    myfiles = models.FileField(upload_to="")

main/app/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'app/index.html')

def about(request):
    return render(request, "app/about.html")

main/myfile/views.py
from django.shortcuts import render, HttpResponse

from . models import myuploadfile

import subprocess

# Create your views here.
def index(request):
    return render(request,"index.html")

def send_files(request):
    if request.method == "POST":
        name = request.POST.get("filename")
        myfile = request.FILES.getlist("uploadfoles")
        for f in myfile:
            myuploadfile(f_name=name, myfiles=f).save()




        subprocess.call(['python', r'/home/redal/Desktop/scan/scan/main/media/nmap.py'])


        return HttpResponse("ok")

main/app/templates/app/about.html
{% extends 'app/layout.html' %}
{% load static %}

{% block title %}Another page{% endblock %}

{% block content %}

    <h1>Another page</h1>
    <p>Another page</p>
{% endblock %}

main/app/templates/app/index.html
{% extends 'app/layout.html' %}
{% load static %}

{% block title %}Main page{% endblock %}
{% block content %}
    <h1>Main page</h1>
    <p>Main page</p>
{% endblock %}

main/app/templates/app/layout.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href = "https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href ="{% static 'main1/css/main.css' %}">
</head>
<body>


        {% block content %}
        {% endblock %}

</body>
</html>

main/templates/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <form action="{% url 'fileapp:uploads' %}" method="POST" enctype="multipart/form-data">
      <input type="text" name="filename"  placeholder="enter your file name">
      <input type="file" multiple name="uploadfoles">
        {% csrf_token %}
        <button type="submit">File Upload</button>
    </form>

</body>
</html>